### ISSUE TITLE
waterline validation error

### ISSUE THREAD

**Issue by ariutta** [agmoyano/OpenIDConnect#18]
The waterline validation error at the bottom is shown in the terminal when you click the "Get Token" button on the "Test Auth Flows" page ```http://localhost:3001/test?code=CODE_VALUE``` in the example. It's coming from [this line](https://github.com/agmoyano/OpenIDConnect/blob/db34de850500a496440490fc0fccb2fc182c811d/index.js#L186). Making it not required removes the error, as in this [temporary fix](https://github.com/ariutta/OpenIDConnect/blob/1c6b91ebc7e97ec94bf8aa38723ecc7a0dd303dd/index.js#L187), but should it be required?

```bash
GET /test?code=94dcf9cee9d3665e37d8408542e03875 200 80.880 ms - 1056
Unhandled rejection Error (E_VALIDATION) :: 1 attribute is invalid
    at WLValidationError.WLError (/Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/lib/waterline/error/WLError.js:33:18)
    at new WLValidationError (/Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/lib/waterline/error/WLValidationError.js:20:28)
    at /Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/lib/waterline/query/validate.js:45:43
    at allValidationsChecked (/Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/lib/waterline/core/validations.js:203:5)
    at done (/Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/node_modules/async/lib/async.js:135:19)
    at /Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/node_modules/async/lib/async.js:32:16
    at /Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/lib/waterline/core/validations.js:194:14
    at done (/Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/node_modules/async/lib/async.js:135:19)
    at /Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/node_modules/async/lib/async.js:32:16
    at /Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/lib/waterline/core/validations.js:157:64
    at /Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/node_modules/async/lib/async.js:124:9)
    at validate (/Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/lib/waterline/core/validations.js:156:11)
    at /Users/ariutta/Sites/OpenIDConnect-master/node_modules/modelling/node_modules/waterline/node_modules/async/lib/async.js:125:13
```

**Comment by markkopaas** [comment]
When you try to exchange code to access token and refresh token, then the
both of these remain related to the code(i.e. auth object). At least it has
been the idea. So it appears to be bug that refresh token is created
without token object. Are you willing to research more?

Markko

**Comment by ariutta** [comment]
Thanks for the tip. Yes, I will try to make time to dig into it more within
the next two weeks or so.

**Comment by ariutta** [comment]
So it looks as if this happens:

GET /test?code=abc123... 200
Create auth, access and refresh models. This works.

POST /user/token 200

GET /test?code=abc123... 200
Try to create refresh model for a second time, but only pass in ```{ auth: null }``` for values. This throws the error.

Not sure what's going on with the second GET.
