### ISSUE TITLE
openid-connect-example.js fails on modelling setup

### ISSUE THREAD

**Issue by fiddur** [agmoyano/OpenIDConnect#19]
I've made `npm install` in both main dir and example.  It seems to be unable to construct the datamodes.  There are so many layers of abstraction that I don't know where to start looking for the missing object.  I get this:

```bash
$ npm start

> openid-connect-example@0.0.3 start /home/fiddur/OpenIDConnect/examples
> node openid-connect-example.js


/home/fiddur/OpenIDConnect/node_modules/modelling/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/utils.js:47
  return hop.call(obj, prop);
             ^
TypeError: Cannot convert null to object
    at hasOwnProperty (native)
    at exports.object.hasOwnProperty (/home/fiddur/OpenIDConnect/node_modules/modelling/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/utils.js:47:14)
    at Attributes.normalizeIdentity (/home/fiddur/OpenIDConnect/node_modules/modelling/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/attributes.js:141:6)
    at Attributes.normalize (/home/fiddur/OpenIDConnect/node_modules/modelling/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/attributes.js:69:8)
    at /home/fiddur/OpenIDConnect/node_modules/modelling/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/attributes.js:37:23
    at Array.forEach (native)
    at new Attributes (/home/fiddur/OpenIDConnect/node_modules/modelling/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/attributes.js:36:15)
    at new module.exports (/home/fiddur/OpenIDConnect/node_modules/modelling/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema.js:27:17)
    at Waterline.initialize (/home/fiddur/OpenIDConnect/node_modules/modelling/node_modules/waterline/lib/waterline.js:107:17)
    at start (/home/fiddur/OpenIDConnect/node_modules/modelling/index.js:257:15)
    at Object.modelling.done (/home/fiddur/OpenIDConnect/node_modules/modelling/index.js:274:5)
    at Object.modelling (/home/fiddur/OpenIDConnect/node_modules/modelling/index.js:31:7)
    at EventEmitter.OpenIDConnect (/home/fiddur/OpenIDConnect/index.js:237:20)
    at Object.exports.oidc (/home/fiddur/OpenIDConnect/index.js:1167:12)
    at Object.<anonymous> (/home/fiddur/OpenIDConnect/examples/openid-connect-example.js:36:32)
    at Module._compile (module.js:456:26)
```

OpenIDConnect npm install gave versions:
```
$ npm install
npm WARN deprecated extend@1.1.3: Please update to the latest version.
extend@1.1.3 node_modules/extend

jwt-simple@0.1.0 node_modules/jwt-simple

clean-obj@0.1.2 node_modules/clean-obj

q@0.9.6 node_modules/q

lodash@3.9.1 node_modules/lodash

base64url@1.0.4 node_modules/base64url
├── concat-stream@1.4.8 (inherits@2.0.1, typedarray@0.0.6, readable-stream@1.1.13)
└── meow@2.0.0 (object-assign@1.0.0, minimist@1.1.1, camelcase-keys@1.0.0, indent-string@1.2.1)

sails-redis@0.10.3 node_modules/sails-redis
├── waterline-errors@0.10.1
├── waterline-cursor@0.0.5
├── async@0.9.2
├── redis@0.12.1
├── lodash@2.4.2
└── waterline-criteria@0.10.7 (include-all@0.1.6)

modelling@0.0.2 node_modules/modelling
├── express@4.12.4 (merge-descriptors@1.0.0, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, cookie@0.1.2, fresh@0.2.4, escape-html@1.0.1, range-parser@1.0.2, content-type@1.0.1, finalhandler@0.3.6, vary@1.0.0, parseurl@1.3.0, serve-static@1.9.3, content-disposition@0.5.0, path-to-regexp@0.1.3, depd@1.0.1, qs@2.4.2, on-finished@2.2.1, etag@1.6.0, proxy-addr@1.0.8, send@0.12.3, debug@2.2.0, accepts@1.2.7, type-is@1.6.2)
└── waterline@0.10.21 (async@0.9.2, bluebird@2.9.25, deep-diff@0.3.2, switchback@1.1.3, waterline-schema@0.1.17, waterline-criteria@0.11.1, anchor@0.10.2, prompt@0.2.14)
```

...and example npm install:
```
$ npm install
extend@2.0.1 node_modules/extend

cookie-parser@1.3.5 node_modules/cookie-parser
├── cookie@0.1.3
└── cookie-signature@1.0.6

method-override@2.3.3 node_modules/method-override
├── methods@1.1.1
├── vary@1.0.0
├── parseurl@1.3.0
└── debug@2.2.0 (ms@0.7.1)

connect-redis@2.3.0 node_modules/connect-redis
├── redis@0.12.1
└── debug@1.0.4 (ms@0.6.2)

morgan@1.5.3 node_modules/morgan
├── basic-auth@1.0.1
├── depd@1.0.1
├── on-finished@2.2.1 (ee-first@1.1.0)
└── debug@2.2.0 (ms@0.7.1)

express-session@1.11.2 node_modules/express-session
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── cookie@0.1.2
├── on-headers@1.0.0
├── parseurl@1.3.0
├── crc@3.2.1
├── uid-safe@2.0.0 (base64-url@1.2.1)
├── depd@1.0.1
└── debug@2.2.0 (ms@0.7.1)

body-parser@1.12.4 node_modules/body-parser
├── content-type@1.0.1
├── bytes@1.0.0
├── depd@1.0.1
├── raw-body@2.0.1 (bytes@2.0.1)
├── qs@2.4.2
├── on-finished@2.2.1 (ee-first@1.1.0)
├── debug@2.2.0 (ms@0.7.1)
├── iconv-lite@0.4.8
└── type-is@1.6.2 (media-typer@0.3.0, mime-types@2.0.12)

errorhandler@1.3.6 node_modules/errorhandler
├── escape-html@1.0.1
└── accepts@1.2.7 (negotiator@0.5.3, mime-types@2.0.12)

express@4.0.0 node_modules/express
├── methods@0.1.0
├── parseurl@1.0.1
├── utils-merge@1.0.0
├── merge-descriptors@0.0.2
├── escape-html@1.0.1
├── debug@0.8.1
├── cookie-signature@1.0.3
├── range-parser@1.0.0
├── fresh@0.2.2
├── qs@0.6.6
├── buffer-crc32@0.2.1
├── cookie@0.1.0
├── path-to-regexp@0.1.2
├── type-is@1.0.0 (mime@1.2.11)
├── accepts@1.0.0 (negotiator@0.3.0, mime@1.2.11)
├── send@0.2.0 (mime@1.2.11)
└── serve-static@1.0.1 (send@0.1.4)
```

...all in all, really a lot of dependencies for a protocol implementation :)

**Comment by fiddur** [comment]
It could perhaps be related to this: https://github.com/balderdashy/waterline/issues/480

In that issue the poster had an empty association…  Could it be the same here?

**Comment by puco** [comment]
And yesterday (2015-05-19) it was working

**Comment by fiddur** [comment]
Going into node_modules/modelling and changing waterline from git to 0.10.20 works.  I guess modelling depending on a git endpoint rather than a version makes OpenIDConnect very unstable.

**Comment by agmoyano** [comment]
Ok, thanks for reporting.. I'll change that dependency in modelling.
