### ISSUE TITLE
example is broken

### ISSUE THREAD

**Issue by mattbailey** [agmoyano/OpenIDConnect#22]
I think this is a dependency problem, since a good deal of the package.json dependencies are ``"*"``

Straight up clone this repo, npm install in both the main directory and example, start up a redis-server, run example, you get this:

```
node openid-connect-example.js
/Users/Matt/src/OpenIDConnect/node_modules/modelling/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/utils.js:47
  return hop.call(obj, prop);
             ^
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (native)
    at exports.object.hasOwnProperty (/Users/Matt/src/OpenIDConnect/node_modules/modelling/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/utils.js:47:14)
    at Attributes.normalizeIdentity (/Users/Matt/src/OpenIDConnect/node_modules/modelling/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/attributes.js:141:6)
    at Attributes.normalize (/Users/Matt/src/OpenIDConnect/node_modules/modelling/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/attributes.js:69:8)
    at /Users/Matt/src/OpenIDConnect/node_modules/modelling/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/attributes.js:37:23
    at Array.forEach (native)
    at new Attributes (/Users/Matt/src/OpenIDConnect/node_modules/modelling/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/attributes.js:36:15)
    at new module.exports (/Users/Matt/src/OpenIDConnect/node_modules/modelling/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema.js:27:17)
    at Waterline.initialize (/Users/Matt/src/OpenIDConnect/node_modules/modelling/node_modules/waterline/lib/waterline.js:107:17)
    at start (/Users/Matt/src/OpenIDConnect/node_modules/modelling/index.js:257:15)
    at Object.modelling.done (/Users/Matt/src/OpenIDConnect/node_modules/modelling/index.js:274:5)
    at Object.modelling (/Users/Matt/src/OpenIDConnect/node_modules/modelling/index.js:31:7)
    at EventEmitter.OpenIDConnect (/Users/Matt/src/OpenIDConnect/index.js:237:20)
    at Object.exports.oidc (/Users/Matt/src/OpenIDConnect/index.js:1173:12)
    at Object.<anonymous> (/Users/Matt/src/OpenIDConnect/examples/openid-connect-example.js:36:32)
    at Module._compile (module.js:460:26)
```

**Comment by petermikitsh** [comment]
+1, having the same issue with same speculations. A package isn't useful if you can't run the example...

**Comment by cfhughes** [comment]
Any answer for this? Same thing happened for me.

**Comment by Yatufo** [comment]
Even after running npm install modelling --save
I get:

 node openid-connect-example.js 
module.js:338
    throw err;
          ^
Error: Cannot find module 'modelling'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/alex/dev/OpenIDConnect/index.js:13:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by agmoyano** [comment]
Hi all, sorry it took so long, but now it should be fixed.

Cheers
