### ISSUE TITLE
Timeout crash again

### ISSUE THREAD

**Issue by steverc** [agmoyano/OpenIDConnect#31]
(Cannot reopen my previous issue #28 so I opened a new one)
It looks like the fix added in c0965daa6a17ca737aad0b566ece31ae1bd7ef43 is not working, I had the crash again: auth object exists, but auth.access is undefined, so access to auth.access.length crashes the server.
My use case is the following: start server, open browser and authenticate, close browser, keep the server running. When timeout expires I have the crash...

**Comment by steverc** [comment]
Hi again, an hint on this issue: is it simply a syntax error? The auth model is defined with attributes "accessTokens" and refreshTokens (see https://github.com/agmoyano/OpenIDConnect/blob/master/index.js#L157), while you check auth.access and auth.refresh (https://github.com/agmoyano/OpenIDConnect/blob/master/index.js#L955 and https://github.com/agmoyano/OpenIDConnect/blob/master/index.js#L916)...

**Comment by dash-** [comment]
Experiencing same issue.  auth.access is invalid after timeout.

Error is:

/oidcServer/node_modules/openid-connect/index.js:954
                                                if(auth && !auth.access.length && !auth.refresh.length) {
                                                                       ^

TypeError: Cannot read property 'length' of undefined
  at /oidcServer/node_modules/openid-connect/index.js:954:72
  at wrapper (/oidcServer/node_modules/openid-connect/node_modules/modelling/node_modules/waterline/node_modules/lodash/index.js:3602:19)
  at applyInOriginalCtx (/oidcServer/node_modules/openid-connect/node_modules/modelling/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
  at wrappedCallback (/oidcServer/node_modules/openid-connect/node_modules/modelling/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
  at callback.success (/oidcServer/node_modules/openid-connect/node_modules/modelling/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
  at _switch (/oidcServer/node_modules/openid-connect/node_modules/modelling/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
  at returnResults (/oidcServer/node_modules/openid-connect/node_modules/modelling/node_modules/waterline/lib/waterline/query/finders/basic.js:180:9)
  at /oidcServer/node_modules/openid-connect/node_modules/modelling/node_modules/waterline/lib/waterline/query/finders/basic.js:91:16
  at /oidcServer/node_modules/openid-connect/node_modules/modelling/node_modules/waterline/lib/waterline/query/finders/operations.js:77:45
  at wrapper (/oidcServer/node_modules/openid-connect/node_modules/modelling/node_modules/waterline/node_modules/lodash/index.js:3602:19)
  at applyInOriginalCtx (/oidcServer/node_modules/openid-connect/node_modules/modelling/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
  at wrappedCallback (/oidcServer/node_modules/openid-connect/node_modules/modelling/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
  at callback.success (/oidcServer/node_modules/openid-connect/node_modules/modelling/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
  at _switch (/oidcServer/node_modules/openid-connect/node_modules/modelling/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
  at Cursor.attachRecords (/oidcServer/node_modules/sails-mongo/node_modules/waterline-cursor/cursor/cursor.js:117:10)
  at afterPopulateBuffers (/oidcServer/node_modules/sails-mongo/node_modules/waterline-cursor/cursor/cursor.js:55:10)
  at /oidcServer/node_modules/sails-mongo/node_modules/waterline-cursor/node_modules/async/lib/async.js:451:17
  at /oidcServer/node_modules/sails-mongo/node_modules/waterline-cursor/node_modules/async/lib/async.js:441:17
  at _each (/oidcServer/node_modules/sails-mongo/node_modules/waterline-cursor/node_modules/async/lib/async.js:46:13)
  at Immediate.taskComplete (/oidcServer/node_modules/sails-mongo/node_modules/waterline-cursor/node_modules/async/lib/async.js:440:13)
  at processImmediate [as _immediateCallback] (timers.js:374:17)
